version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://uye.onder.org.tr/api
    container_name: dernek-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=https://uye.onder.org.tr/api
    depends_on:
      - backend
    networks:
      - dernek-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dernek-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=dernek_secure_password_2024
      - DB_NAME=dernek_system
      - JWT_SECRET=dernek_super_secret_key_production_2024
      - JWT_EXPIRE=7d
      - MAX_FILE_SIZE=10485760
      - UPLOAD_PATH=./uploads
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - mysql
    networks:
      - dernek-network

  mysql:
    image: mysql:8.0
    container_name: dernek-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=dernek_secure_password_2024
      - MYSQL_DATABASE=dernek_system
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "3306:3306"
    networks:
      - dernek-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dernek-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=dernek_secure_password_2024
    depends_on:
      - mysql
    networks:
      - dernek-network

networks:
  dernek-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  uploads_data:
    driver: local